# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.1.10"
  port_number: 30003

HOME_JOINTS:
  - -62.78
  - -91.07
  - -121.67
  - -46.41
  - 115.78
  - 95.66

HOME_POSE:
  - 0.179
  - -0.615
  - 0.404
  - 3.14
  - 0
  - 0

JOINT_ACC:
  - 0.7
JOINT_VEL:
  - 1.6

PICK_Z: 0.
PLACE_Z: 0.08
CALIBRATION_DIR: "/data/calibration_data/ur10e-realsense.npz"
