# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.1.27"
  port_number: 30003

HOME_JOINTS:
  - -72.58
  - -74.45
  - -94.91
  - -100.72
  - 89.25
  - 107.34

HOME_POSE:
  - 0.012
  - -0.3085
  - 0.46689
  - 3.14
  - 0
  - 0

JOINT_ACC:
  - 1.6
JOINT_VEL:
  - 0.7

PICK_Z: 0.34
PLACE_Z: 0.40
CALIBRATION_DIR: "/data/calibration_data/ur5-realsense.npz"
